services:
  app:
    build: .
    command: flask run --debug
    ports:
      - "${HOST_PORT}:5000"
    environment:
      FLASK_RUN_HOST: 0.0.0.0
    develop:
      watch:
        - action: sync
          path: .
          target: /app

# docker compose up --watch --remove-orphans
