services:
  db:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
  app:
    build: .
    command: gunicorn -w 2 -b :5000 'app:app'
    ports:
      - "${HOST_PORT}:5000"
    environment:
      FLASK_RUN_HOST: 0.0.0.0

# docker compose up --build -d
